### ISSUE TITLE
Replace omega with lia

### ISSUE THREAD

**Issue by palmskog** [anton-trunov/alea#9]
Since the omega tactic is bound to be deprecated in future Coq versions, and lia is already an almost complete replacement in 8.11 (minimum version for this project), it should be a straightforward decision to do a replacement.

**Comment by anton-trunov** [comment]
FTR, a trivial replacement like
- `omega` -> `lia`,
- `Require Import Omega` -> `Require Import Lia`

did not really work. Some lemmas failed to typecheck due to a number of subgoals not solved. Looks like `Require Import Omega Lia` fixes it, but compilation becomes much slower. Upshot: needs further investigation.
